# Criando N-dimensional arrays


In [1]:
import numpy as np
import random

### Transformando uma lista em numpy array

### Array com uma dimensão (apenas umas lista)
+ numpy.asarray(object, dtype=None, order=None)
+ numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    + object : array_like
    + dtype : data-type, optional
    + copy : bool, optional
    + order : {‘K’, ‘A’, ‘C’, ‘F’}, optional
    + subok : bool, optional
    + ndmin : int, optional
    + Returns: An array object satisfying the specified requirements.
+ a diferença entre np.array e np.asarray é que para o segundo caso não há cópia do array original

In [2]:
lista_a = [1.9,8,765,13.567]

In [3]:
array_a = np.array(lista_a)

In [4]:
array_a

array([   1.9  ,    8.   ,  765.   ,   13.567])

In [5]:
np.asarray(lista_a)

array([   1.9  ,    8.   ,  765.   ,   13.567])

In [6]:
np.array([random.random() for x in range(5)], ndmin=1)

array([ 0.55264645,  0.40725869,  0.28658218,  0.94417827,  0.66924217])

In [7]:
np.array([random.random() for x in range(5)], ndmin=2)

array([[ 0.91919927,  0.50257584,  0.55375877,  0.35942114,  0.37766699]])

### 1.1.2 Array com n dimensões (cada lista uma dimensão)

In [8]:
import random

In [9]:
'''Lista de listas'''
lista_a_1 = [random.randrange(1,10) for x in range(5)]
lista_a_2 = [random.randrange(1,100) for x in range(5)]
lista_a_3 = [random.randrange(50,100) for x in range(5)]
array_a_3d = np.array([lista_a_1, lista_a_2, lista_a_3]) # cada dimensão é uma lista




In [10]:
array_a_3d

array([[ 9,  1,  1,  6,  2],
       [92, 83, 63, 39,  4],
       [50, 77, 85, 56, 95]])

In [11]:
array_a_3d.ndim, array_a_3d.shape

(2, (3, 5))

In [12]:
'''Teste: é possível fazer com tamanhos diferentes?
Mais ou menos! Foi criado um array unidimensional, com listas como elementos'''
lista_b_1 = [random.randrange(1,10) for x in range(3)]
lista_b_2 = [random.randrange(1,100) for x in range(4)]
lista_b_3 = [random.randrange(50,100) for x in range(5)]
array_b_3d = np.array([lista_b_1, lista_b_2, lista_b_3]) # cada dimensão é uma lista


In [13]:
array_b_3d

array([[1, 6, 7], [46, 91, 99, 71], [68, 78, 67, 73, 76]], dtype=object)

In [14]:
array_b_3d.ndim,array_b_3d.shape #atenção, tuple de uma só variável é mostrado com um número seguido de uma virgula dentro de parênteses.

(1, (3,))

In [15]:
'''Comparando as propriedades'''
print('array_a_3d')
print(array_a_3d)
print('array_a_3d.ndim =',array_b_3d.ndim)
print('array_a_3d.shape =', array_b_3d.shape)

print('\narray_b_3d')
print(array_b_3d)
print('array_b_3d.ndim =',array_b_3d.ndim)
print('array_b_3d.shape =',array_b_3d.shape)


array_a_3d
[[ 9  1  1  6  2]
 [92 83 63 39  4]
 [50 77 85 56 95]]
array_a_3d.ndim = 1
array_a_3d.shape = (3,)

array_b_3d
[[1, 6, 7] [46, 91, 99, 71] [68, 78, 67, 73, 76]]
array_b_3d.ndim = 1
array_b_3d.shape = (3,)


# Criando arrays com zeros np.zeros()
+ numpy.zeros(shape, dtype=float, order='C'):
    + shape : int or sequence of ints
    + dtype : data-type, optional
    + order : {‘C’, ‘F’}, optional
    + Returns: Array of zeros with the given shape, dtype, and order.


In [16]:
np.zeros(5) #unidimensional

array([ 0.,  0.,  0.,  0.,  0.])

In [17]:
np.zeros(5, dtype=np.int) #unidimensional, especificando o tipo

array([0, 0, 0, 0, 0])

In [18]:
np.zeros([5,3], dtype=np.int) # shape pode ser indicado via lista

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [19]:
np.zeros((5,3), dtype=np.int) # ou tuple

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
np.zeros(np.array([2,2])) #mesmo outro np.array

array([[ 0.,  0.],
       [ 0.,  0.]])

# Criando arrays com um np.ones()
+ numpy.zeros(shape, dtype=float, order='C'):
    + shape : int or sequence of ints
    + dtype : data-type, optional
    + order : {‘C’, ‘F’}, optional
    + Returns: Array of zeros with the given shape, dtype, and order.

In [21]:
np.ones(3)

array([ 1.,  1.,  1.])

In [22]:
np.ones([2,4])

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [23]:
np.ones([4,2], dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

# Empty, Ones e zeros like
+ numpy.zeros_like(a, dtype=None, order='K', subok=True)
+ numpy.ones_like(a, dtype=None, order='K', subok=True)
+ numpy.empty_like(a, dtype=None, order='K', subok=True)¶
    + a : array_like (The shape and data-type of a define these same attributes of the returned array.)
    + dtype : data-type, optional (Overrides the data type of the result.)
    + order : {‘C’, ‘F’, ‘A’, or ‘K’}, optional
    + subok : bool, optional.
    + Returns: Array of ones/zeros with the same shape and type as a.

In [24]:
array_a_3d.shape

(3, 5)

In [25]:
np.zeros_like(array_a_3d)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [26]:
np.zeros_like(array_a_3d).shape

(3, 5)

In [27]:
np.ones_like(array_a_3d)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [28]:
np.zeros_like(array_a_3d).shape

(3, 5)

In [29]:
np.empty_like(array_a_3d)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [30]:
np.empty_like(array_a_3d).shape

(3, 5)

# Criando um array sem valores específicos - np.empty()
+ numpy.empty(shape, dtype=float, order='C')
    + shape : int or tuple of int
    + dtype : data-type, optional
    + order : {‘C’, ‘F’}, optional
    + out : Array of uninitialized (arbitrary) data of the given shape, dtype, and order. Object arrays will be initialized to None.

In [31]:
np.empty([2, 2])

array([[ 0.,  0.],
       [ 0.,  0.]])

In [32]:
np.empty([2, 2], dtype=int)

array([[0, 1],
       [2, 3]])

In [33]:
np.empty([3, 2], dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [34]:
np.empty((3, 2), dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

# np.arange()
+ similar a range()
+ Return evenly spaced values within a given interval.
    + numpy.arange([start, ]stop, [step, ]dtype=None)
        + start : number, optional
        + stop : number
        + step : number, optional
        + dtype : dtype
        + Returns: Array of evenly spaced values.
+ For floating point arguments, the length of the result is ceil((stop - start)/step). Because of floating point overflow, this rule may result in the last element of out being greater than stop.

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(10,100,4)

array([10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66, 70, 74,
       78, 82, 86, 90, 94, 98])

In [37]:
np.arange(0,1,0.03) #step como decimal

array([ 0.  ,  0.03,  0.06,  0.09,  0.12,  0.15,  0.18,  0.21,  0.24,
        0.27,  0.3 ,  0.33,  0.36,  0.39,  0.42,  0.45,  0.48,  0.51,
        0.54,  0.57,  0.6 ,  0.63,  0.66,  0.69,  0.72,  0.75,  0.78,
        0.81,  0.84,  0.87,  0.9 ,  0.93,  0.96,  0.99])

# np.eye()
+ numpy.eye(N, M=None, k=0, dtype=<type 'float'>)
    + N : Number of rows in the output.
    + M : int, optional. Number of columns in the output. If None, defaults to N.
    + k : int, optional. Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.
    + dtype : data-type, optional
    + Returns: An array where all elements are equal to zero, except for the k-th diagonal, whose values are equal to one.

In [38]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [39]:
np.eye(3,5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.]])

In [40]:
np.eye(5,k=2)

array([[ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

# np.identity()
+ numpy.identity(n, dtype=None)
    + n : Number of rows (and columns) in n x n output.
    + dtype : data-type, optional
    + Returns: n x n array with its main diagonal set to one, and all other elements 0.

In [41]:
np.identity(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [42]:
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])